#!/bin/bash
FTP_BASE="/srv/http/repo/public/temprepo"
ARCH_BASE="/srv/http/repo/public/temprepo"
SVNREPO="/var/abs"

# Repos from Arch
ARCHREPOS=('core' 'testing') #'extra' 'community'  'testing' 'multilib')
# Official Parabola repos
OURREPOS=('libre' 'libre-testing')
# User repos
USERREPOS=('~fauno' '~smv' '~xihh' '~mtjm')
# Community project repos
PROJREPOS=('social' 'elementary' 'kernels' 'radio' 'security' 'social')
PKGREPOS=(${ARCHREPOS[@]} ${OURREPOS[@]} ${USERREPOS[@]} ${PROJREPOS[@]})
PKGPOOL='pool/packages'
SRCPOOL='sources/packages'

CLEANUP_DESTDIR="$FTP_BASE/old/packages"
CLEANUP_DRYRUN=false
# Time in days to keep moved packages
CLEANUP_KEEP=30

SOURCE_CLEANUP_DESTDIR="$FTP_BASE/old/sources"
SOURCE_CLEANUP_DRYRUN=false
# Time in days to keep moved sourcepackages
SOURCE_CLEANUP_KEEP=30

REQUIRE_SIGNATURE=true

LOCK_DELAY=10
LOCK_TIMEOUT=300

STAGING="$FTP_BASE/staging"
TMPDIR="/tmp"
ARCHARCHES=(i686 x86_64)
ARCHES=(${ARCHARCHES[@]} mips64el)
DBEXT=".db.tar.gz"
FILESEXT=".files.tar.gz"
PKGEXT=".pkg.tar.?z"
SRCEXT=".src.tar.gz"

MAKEPKGCONF="/etc/makepkg.conf"
BLACKLIST_FILE="$HOME/blacklist/blacklist.txt"
