#!/bin/bash
FTP_BASE="/home/parabolavnx/parabolagnulinux.org/repo"
ARCH_BASE="/home/parabolavnx/parabolagnulinux.org/repo"
SVNREPO="/home/parabolavnx/parabolagnulinux.org/abslibre"

ARCHREPOS=('core' 'extra' 'community'  'testing' 'multilib')
PKGREPOS=(${ARCHREPOS[@]} 'libre' 'libre-testing' 'social' 'sugar' 'elementary' '~fauno' '~xihh')
PKGPOOL='pool/packages'
SRCPOOL='sources/packages'

CLEANUP_DESTDIR="$FTP_BASE/old/packages"
CLEANUP_DRYRUN=false
# Time in days to keep moved packages
CLEANUP_KEEP=30

SOURCE_CLEANUP_DESTDIR="$FTP_BASE/old/sources"
SOURCE_CLEANUP_DRYRUN=false
# Time in days to keep moved sourcepackages
SOURCE_CLEANUP_KEEP=30

REQUIRE_SIGNATURE=false

LOCK_DELAY=10
LOCK_TIMEOUT=300

STAGING="$FTP_BASE/staging"
TMPDIR="$HOME/tmp"
ARCHARCHES=(i686 x86_64)
ARCHES=(${ARCHARCHES[@]} mips64el)
DBEXT=".db.tar.gz"
FILESEXT=".files.tar.gz"
PKGEXT=".pkg.tar.?z"
SRCEXT=".src.tar.gz"

MAKEPKGCONF="$HOME/etc/makepkg.conf"
BLACKLIST_FILE="$HOME/parabolagnulinux.org/docs/blacklist.txt"
