#!/bin/bash
# Creates the repo structure defined in config

source "$(dirname "$(readlink -e "$0")")/config"

mkdir -p -- "${FTP_BASE}"/{"${PKGPOOL}","${SRCPOOL}"} "${ARCH_BASE}" "${CLEANUP_DESTDIR}" "${SOURCE_CLEANUP_DESTDIR}" "${STAGING}"

"$(dirname "$(readlink -e "$0")")/create-repo" "${PKGREPOS[@]}"
