#!/bin/bash
# Creates repository structure

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if [ $# -eq 0 ]; then
    msg "Usage: ${0##*/} repo1 [repo2 ... repoX]"
    exit 1
fi

msg "Creating repos..."
for _repo in $@; do
    msg2 "Creating [${_repo}]"
    mkdir -p "${FTP_BASE}/staging/${_repo}" || \
        error "Failed creating staging dir"

    for _arch in ${ARCHES[@]}; do
        mkdir -p "${FTP_BASE}/${_repo}/os/${_arch}" || \
            error "Failed creating ${_arch} dir"
    done
done

msg "Don't forget to add them to the PKGREPOS array on %s/config" "$(dirname "$(readlink -e "$0")")"
