#!/bin/bash
# Creates repository structure

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if [ $# -eq 0 ]; then
	msg "Usage: %s repo1 [repo2 ... repoX]" "${0##*/}"
	exit 1
fi

msg "Creating repos..."
for _repo in "$@"; do
	msg2 "Creating [%s]" "${_repo}"
	for _arch in "${ARCHES[@]}"; do
		mkdir -p "${FTP_BASE}/${_repo}/os/${_arch}" || \
			error "Failed creating %s dir" "${_arch}"
	done
done

msg "Don't forget to add them to the PKGREPOS array on %s" "$(dirname "$(readlink -e "$0")")/config"
