#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if [ $# -ge 1 ]; then
	error "Calling %s with a specific repository is not supported" "${0##*/}"
	exit 1
fi

# TODO: this might lock too much (architectures)
for repo in "${repos[@]}"; do
	for pkgarch in "${ARCHES[@]}"; do
		repo_lock "${repo}" "${pkgarch}" || exit 1
	done
done

msg "Check nonfree in repo:"
libreblacklist update
nonfree=($(libreblacklist get-pkg | sort -u))
for repo in "${ARCHREPOS[@]}"; do
	for pkgarch in "${ARCHES[@]}"; do
		msg2 "%s %s" "$repo" "$pkgarch"
		if [ ! -f "${FTP_BASE}/${repo}/os/${pkgarch}/${repo}${DBEXT}" ]; then
			continue
		fi
		unset dbpkgs
		unset cleanpkgs
		cleanpkgs=()
		dbpkgs=($(bsdtar -xOf "${FTP_BASE}/${repo}/os/${pkgarch}/${repo}${DBEXT}" | awk '/^%NAME%/{getline;print}' | sort -u ))
		for pkgname in "${dbpkgs[@]}"; do
			if in_array "${pkgname}" "${nonfree[@]}"; then
				cleanpkgs+=("${pkgname}")
			fi
		done
		if [ ${#cleanpkgs[@]} -ge 1 ]; then
			msg2 "Nonfree: %s" "${cleanpkgs[*]}"
			arch_repo_remove "${repo}" "${pkgarch}" "${cleanpkgs[@]}"
		fi
	done
done

for repo in "${repos[@]}"; do
	for pkgarch in "${ARCHES[@]}"; do
		repo_unlock "${repo}" "${pkgarch}"
	done
done
