#!/usr/bin/env python2
#-*- encoding: utf-8 -*-
from filter import *
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="db-check-nonfree-in-db",
        description="Cleans nonfree files on repo",)

    parser.add_argument("-k", "--blacklist-file", type=str,
                        help="File containing blacklisted names",
                        required=True,)

    parser.add_argument("-b", "--database", type=str,
                          help="dabatase to clean",
                          required=True,)

    args=parser.parse_args()

    if not (args.blacklist_file and args.database):
        parser.print_help()
        exit(1)

    blacklist=listado(args.blacklist_file)
    pkgs=get_pkginfo_from_db(args.database)

    print(" ".join([pkg["name"] for pkg in pkgs if pkg["name"] in blacklist]))
