#!/bin/bash

set -e

source "$(dirname "$(readlink -e "$0")")/config"
source "$(dirname "$(readlink -e "$0")")/db-import-archlinux.conf"

# Steps
# * Sync abs
# * Download blacklist.txt
# * Sync abslibre from abs excluding from blacklist
# * Create repo.abs.tar.gz tarballs

function sync_abs() {
	for ARCH in any i686 x86_64; do
		rsync ${SYNCARGS} ${ABS_SERVER}::abs/${ARCH}/ ${ABS_ROOT}/${ARCH} || return $?
	done

	# fix some permissions
	find "${ABS_ROOT}" -type d -print0 | xargs -0 chmod 755
	find "${ABS_ROOT}" -type f -print0 | xargs -0 chmod 644
}

function get_blacklist() {
	libreblacklist update
	libreblacklist get-pkg | sort -u | \
		sed "s/^/**\//" > ${BLFILE} || {
		printf "[FAILED]\n"
		return 1
	}

	# Prevent using an empty blacklist
	[ $(wc -l ${BLFILE} | cut -d " " -f1) -eq 0 ] && return 1

	printf "[OK]\n"
}

function sync_abs_libre() {

	# Clone ABSLibre git repo
	rm -rf -- "$tmpdir/abslibre"
	git clone "$ABSLIBRE_GIT" "$tmpdir/abslibre"

	# Sync from ABS and then sync from ABSLibre
	printf ":: Syncing ABSLibre...\t"
	if ! rsync ${SYNCARGS} --delete-excluded --exclude-from=${BLFILE} ${ABS_ROOT} ${ABSLIBRE_ROOT}; then
		printf "[FAILED]\n"
		return 1
	fi
	for ARCH in i686 x86_64; do
		if ! rsync -v -mrtq --no-motd --no-p --no-o --no-g --quiet --exclude=.git/ "$tmpdir/abslibre/" ${ABSLIBRE_ROOT}/${ARCH}/; then
			printf "[FAILED]\n"
			return 1
		fi
	done

	# fix some permissions
	find "${ABSLIBRE_ROOT}" -type d -print0 | xargs -0 chmod 755
	find "${ABSLIBRE_ROOT}" -type f -print0 | xargs -0 chmod 644

	printf "[OK]\n"
}

# Create .abs.tar.gz tarballs
create_tarballs() {
	for repo in ${ABSLIBRE_ROOT}/{i686,x86_64}/*; do
		baserepo=${repo##*/}
		arch=$(basename $(dirname $repo))

		# Remove the old one
		mkdir -p $FTP_BASE/$baserepo/os/$arch/
		rm -fv $FTP_BASE/$baserepo/os/$arch/$baserepo.abs.tar.gz
		# Create a new one joining arch and any
		# Remove the first part of the path (it could be $repo but any isn't hit)
		bsdtar -czf $FTP_BASE/$baserepo/os/$arch/$baserepo.abs.tar.gz \
			-s ":${ABSLIBRE_ROOT}/[a-z0-9_]\+/[a-z]\+::" \
			$repo/* ${ABSLIBRE_ROOT}/any/${baserepo}/*

	done
}

main() {
	trap 'rm -rf -- "$tmpdir"' EXIT
	tmpdir=$(mktemp --tmpdir -d "${0##*/}.XXXXXXXXXX")

	BLFILE=${tmpdir}/blacklist.txt
	sync_abs
	get_blacklist
	sync_abs_libre
	create_tarballs
}

main "$@"
