#!/bin/bash
# Copyright (C) 2012  Michał Masłowski  <mtjm@mtjm.eu>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Output a list of repo/package-name-and-version pairs representing
# unsigned packages available for architecture $1 and specified for
# architecture $2 (usually $1 or any, default is to list all).

. "$(dirname $0)/db-functions"
. "$(dirname $0)/config"

if [ $# -lt 1 ]; then
	msg "usage: $(basename $0) <architecture>"
	exit 1
fi

arch=$1
shift

for repo in ${PKGREPOS[@]}
do
    db="${FTP_BASE}/${repo}/os/${arch}/${repo}.db"
    [ -f "$db" ] && "$(dirname $0)/db-list-unsigned-packages.py" "$repo" "$@" < "$db"
done
