#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if (( $# < 3 )); then
	msg "usage: %s <repo> <arch> <pkgname|pkgbase> ..." "${0##*/}"
	exit 1
fi

repo="$1"
arch="$2"
pkgbases=("${@:3}")

if ! check_repo_permission "$repo"; then
	die "You don't have permission to remove packages from %s" "$repo"
fi

if [[ $arch = any ]]; then
	tarches=("${ARCHES[@]}")
else
	tarches=("$arch")
fi

for tarch in "${tarches[@]}"; do
	repo_lock "$repo" "$tarch" || exit 1
done

remove_pkgs=()
for pkgbase in "${pkgbases[@]}"; do
	msg "Removing %s from [%s]..." "$pkgbase" "$repo"

	mapfile -t pkgnames < <(getdbinfo "$repo" "${tarches[0]}" "$pkgbase" NAME)
	remove_pkgs+=("${pkgnames[@]}")

	path="$(xbs releasepath "$pkgbase" "$repo" "$arch")"
	if [[ -d $path ]]; then
		xbs unrelease "$pkgbase" "$repo" "$arch"
	else
		warning "pkgbase '%s' not found in %s for %s; unable to commit removal there" \
			"$pkgbase" "$(xbs name)" "$repo-$arch"
	fi
done

for tarch in "${tarches[@]}"; do
	arch_repo_modify remove "${repo}" "${tarch}" "${remove_pkgs[@]}"
	repo_unlock "$repo" "$tarch"
done
