#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/db-functions"
. "$(dirname "$(readlink -e "$0")")/config"

if [ $# -lt 3 ]; then
	msg "usage: ${0##*/} <repo> <arch> <pkgname|pkgbase> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgbases=("${@:3}")

if ! check_repo_permission $repo; then
	die "You don't have permission to remove packages from ${repo}"
fi

if [ "$arch" == "any" ]; then
	tarches=("${ARCHES[@]}")
else
	tarches=("$arch")
fi

for tarch in "${tarches[@]}"; do
	repo_lock $repo $tarch || exit 1
done

remove_pkgs=()
for pkgbase in "${pkgbases[@]}"; do
	msg "Removing $pkgbase from [$repo]..."

    if [ -d "${SVNREPO}/$repo/$pkgbase" ]; then
        remove_pkgs=($(. "${SVNREPO}/$repo/$pkgbase/PKGBUILD"; echo ${pkgname[@]}))
	else
		warning "$pkgbase not found in ABS(libre)"
		warning "Removing only $pkgbase from the repo"
		warning "If it was a split package you have to remove the others yourself!"
		remove_pkgs+=("$pkgbase")
	fi
done

for tarch in "${tarches[@]}"; do
	arch_repo_remove "${repo}" "${tarch}" "${remove_pkgs[@]}"
	repo_unlock $repo $tarch
done
