#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

if [ $# -lt 3 ]; then
	msg "usage: %s <repo> <arch> <pkgname|pkgbase> ..." "${0##*/}"
	exit 1
fi

repo="$1"
arch="$2"
pkgbases=("${@:3}")

if ! check_repo_permission "$repo"; then
	die "You don't have permission to remove packages from %s" "${repo}"
fi

if [ "$arch" == "any" ]; then
	tarches=("${ARCHES[@]}")
else
	tarches=("$arch")
fi

for tarch in "${tarches[@]}"; do
	repo_lock "$repo" "$tarch" || exit 1
done

remove_pkgs=()
for pkgbase in "${pkgbases[@]}"; do
	msg "Removing %s from [%s]..." "$pkgbase" "$repo"

	if [ -d "${SVNREPO}/$repo/$pkgbase" ]; then
		remove_pkgs+=($(. "${SVNREPO}/$repo/$pkgbase/PKGBUILD"; echo "${pkgname[@]}"))
	else
		warning "%s not found in ABS(libre)" "$pkgbase"
		warning "Removing only %s from the repo" "$pkgbase"
		warning "If it was a split package you have to remove the others yourself!"
		remove_pkgs+=("$pkgbase")
	fi
done

for tarch in "${tarches[@]}"; do
	arch_repo_remove "${repo}" "${tarch}" "${remove_pkgs[@]}"
	repo_unlock "$repo" "$tarch"
done
