#!/bin/bash
# -*- coding: utf-8 -*-

source ./config
source ./local_config
source ./libremessages

for repo in ${PKGREPOS[@]}; do
    for arch in ${ARCHES[@]} 'any'; do
	msg "Syncing ${repo} ${arch}"
	${rsync_list_command} \
	    ${mirror}::${mirrorpath}/${repo}/os/${arch}/ \
	    ${repodir}/${repo}/ > ${rsout_file}
	filter.py -r ${rsync_blacklist} -k ${blacklist} \
	    -f ${rsout_file}
	find ${repodir}/${repo} -name *${PKGEXT} \
	    -fprint ${rsync_not_needed}
	${rsync_update_command} \
	    --exclude-from=${rsync_blacklist} \
	    --exclude-from=${rsync_not_needed}
	    ${mirror}::${mirrorpath}/${repo}/os/${arch}/ \
	    ${repodir}/${repo}/
    done
    for arch in ${ARCHES[@]}; do
	if [ -r ${repodir}/${repo}/os/${arch}/${repo}${DBEXT} ]; then
	    clean_repo.py -k ${blacklist} -w ${whitelist} \
		-p ${docs_dir}/pending-${repo} \
		-b ${repodir}/${repo}/${repo}${DBEXT}
	fi
	python clean_repo.py -k ${blacklist} -d ${repodir}/${repo}
    done
done

db-update
ftpdir-cleanup

get_license.sh
