#! /bin/bash
# Copyright (C) 2014 Joseph Graham <joseph@t67.eu>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script depends on `mktorrent'

username=$( id -un )

case "${username}" in
    repo | root )
        true
        ;;
    * )
        echo "This script must be run as repo user or root user."
        echo "ByeBye!"
        exit 1
        ;;
esac

# pacman doesn't support multiple different packages of the same name,
# so it's OK to just stuff all the torrents into a single directory.
torrent_location='/srv/http/repo/public/torrents/'
public_location='/srv/http/repo/public/'

# Tracker announce URL
tracker='http://t67.eu:6969/announce'  # t67.eu is run by Xylon

# All mirrors go here
declare -a url_prefixes=('http://repo.parabolagnulinux.org/' 'https://parabola.goodgnus.com.ar/' 'http://mirror.yandex.ru/mirrors/parabola/' 'http://alfplayer.com/parabola/')

cd "${torrent_location}"

find "${public_location}" -name 'os' -type 'd' |
while read dir
do
    find "${dir}" -name '*\.pkg\.tar\.xz' |
    while read pkg
    do
	pkg_name="${pkg##*/}"

        if [[ -h "${pkg}" ]]  # check if it's a symbolic link
        then
            # We get the target of the symlink
            pkg=$( readlink -f "${pkg}" )
        fi

	if ! [[ -f "${torrent_location}${pkg_name}.torrent" ]]
	then
            # We need to make a comma seperated list of webseeds (this is passed
            # as a single argument to mktorrent)
            webseeds=''

            for prefix in "${url_prefixes[@]}"
            do
                webseeds+="${prefix}${pkg#${public_location}},"
            done

            # There should not be a random comma at the end of the webseeds
            webseeds="${webseeds%,}"

	    mktorrent -a "${tracker}" "${pkg}" -w "${webseeds}"  # "${torrent_location}"
	fi
    done
done

if [[ "${username}" == root ]]
then
    chown repo *
fi
